python:
  - "2.7"
  - "3.6"

matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=3.6
  - os: osx
    language: generic
    env: PYTHON=2.7

before_install:
  - travis_get_python.sh
  - pip install -r requirements.txt

script:
  - python test.py

