sudo: required 
python:
  - "2"
  - "3"

matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=3
  - os: osx
    language: generic
    env: PYTHON=2

before_install:
  - sh travis_get_python.sh
  - pip install -r requirements.txt

script:
  - python test.py

